version: '3.8'

services:
  mongodb: 
    image: 'mongo'
    volumes:
      - data:/data/db
  users:
    build:
      context: .
      dockerfile: dockerfiles/app.dockerfile
    ports:
      - 8001:8000
    volumes: 
      - ./services/users:/app
  messages:
    build:
      context: .
      dockerfile: dockerfiles/app.dockerfile
    ports: 
      - 8002:80
    volumes:
      - ./services/messages:/app
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./services/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users
      - messages

volumes:
  data: