version: '3.8'

services:
  mongodb: 
    image: 'mongo'
    volumes:
      - data:/data/db
  users:
    build:
      context: .
      dockerfile: dockerfiles/app.dockerfile
    command: 'uvicorn app:app --host 0.0.0.0 --port 8001 --reload'
    volumes: 
      - ./services/users:/app
  messages:
    build:
      context: .
      dockerfile: dockerfiles/app.dockerfile
    command: 'uvicorn app:app --host 0.0.0.0 --port 8002 --reload'
    volumes:
      - ./services/messages:/app
  speech:
    build: 
      context: .
      dockerfile: dockerfiles/app.dockerfile
    command: 'uvicorn app:app --host 0.0.0.0 --port 8003 --reload'
    volumes:
      - ./services/speech:/app
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./services/nginx.config:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - users
      - messages
      - speech
    
volumes:
  data: